# Generated by Django 2.0.7 on 2018-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_regd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('apntto', models.CharField(max_length=200)),
                ('replydesc', models.CharField(max_length=200)),
            ],
        ),
    ]
