# Generated by Django 2.0.7 on 2018-07-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='apntto',
            new_name='replyto',
        ),
    ]
