# Generated by Django 2.0.7 on 2018-07-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180725_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replyd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=200)),
                ('emailid', models.CharField(max_length=200)),
                ('replyto', models.CharField(max_length=200)),
                ('replydesc', models.CharField(max_length=200)),
            ],
        ),
    ]
