# Generated by Django 2.0.7 on 2018-07-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_replyd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
