# Generated by Django 2.0.7 on 2018-07-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=200)),
                ('replyto', models.CharField(max_length=200)),
                ('replydesc', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Replyd',
        ),
    ]
