# Generated by Django 2.0.7 on 2018-08-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180726_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='apnt',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
