# Generated by Django 2.0.7 on 2018-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_apnt_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
