# Generated by Django 2.0.7 on 2018-08-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_apnt_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='time',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
