# Generated by Django 2.0.7 on 2018-08-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_apnt_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnt',
            name='date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
