# Generated by Django 2.0.7 on 2018-08-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20180808_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnt',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='apnt',
            name='time',
            field=models.TimeField(verbose_name='time published'),
        ),
    ]
