# Generated by Django 2.0.7 on 2018-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20180808_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='regd',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='date',
            field=models.DateField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='time',
            field=models.TimeField(verbose_name='time published'),
        ),
    ]
