from django.urls import path

from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('preg', views.preg, name='preg'),
    path('plogin', views.plogin, name='plogin'),
    path('regcode', views.regcode, name='regcode'),
    path('logincode', views.logincode, name='logincode'),
    path('userdash', views.userdash, name='userdash'),
    path('viewapnt', views.viewapnt, name='viewapnt'),
    path('apntcode', views.apntcode, name='apntcode'),
    path('editapnt', views.editapnt, name='editapnt'),
    path('deleteapnt', views.deleteapnt, name='deleteapnt'),
    path('updateapntcode', views.updateapntcode, name='updateapntcode'),
    path('logout', views.logout, name='logout'),
    path('dreg', views.dreg, name='dreg'),
    path('dlogin', views.dlogin, name='dlogin'),
    path('regdcode', views.regdcode, name='regdcode'),
    path('logindcode', views.logindcode, name='logindcode'),
    path('viewdapnt', views.viewdapnt, name='viewdapnt'),
    path('replycode', views.replycode, name='replycode'),
    path('reply', views.reply, name='reply'),
    path('admin', views.admin, name='admin'),
    path('pdesh', views.pdesh, name='pdesh'),
    path('ddesh', views.ddesh, name='ddesh'),
    path('about', views.about, name='about'),
    path('feedback', views.feedback, name='feedback'),
    path('feedcode', views.feedcode, name='feedcode'),
    path('viewfeed', views.viewfeed, name='viewfeed'),
    path('editfeed', views.editfeed, name='editfeed'),
    path('updatefeed', views.updatefeed, name='updatefeed'),
    path('pflogin', views.pflogin, name='pflogin'),
    path('dflogin', views.dflogin, name='dflogin'),
    path('logindfcode', views.logindfcode, name='logindfcode'),
    path('loginfcode', views.loginfcode, name='loginfcode'),
    path('feeddash', views.feeddash, name='feeddash'),
    path('viewdfeed', views.viewdfeed, name='viewdfeed'),
    path('replyfeed', views.replyfeed, name='replyfeed'),
    path('replyfcode', views.replyfcode, name='replyfcode'),
    path('deletefeed', views.deletefeed, name='deletefeed'),
]